name: Brain-client connect
on: [push]

jobs:
  create_file:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.ohiosstars_dirty_little_secret }}
    steps:
      - run: ssh db2c2023q4_guest_3@brain-client.bigdatateam.org ls
