name: Brain-client connect
on: [push]

jobs:
  create_file:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.ohiosstars_dirty_little_secret }}
    steps:
      - uses: actions/checkout@v2
      - run: echo $ssh_key
