name: Brain-client connect
on: [push]

jobs:
  create_file:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.ohiosstars_dirty_little_secret }}
    steps:
      - run: mkdir -p ~/.ssh
      - run: echo $ssh_key > ~/id_rsa
      - run: chmod 0600 ~/id_rsa
      - run: ssh -o StrictHostKeyChecking=no bdb2c2023q4_guest_3@brain-client.bigdatateam.org ls
