name: Brain-client connect
on: [push]

jobs:
  create_file:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.OHIOSSTARS_DIRTY_LITTLE_SECRET }}
      seed: ${{ vars.SEED }}
    steps:
      - name: Set ssh key
        run: |
          mkdir -p ~/.ssh && \
          echo "$ssh_key" | base64 -d > ~/.ssh/id_rsa && \
          chmod 0600 ~/.ssh/id_rsa
      - name: Run primes.py
        run: python3 ~/primes.py $seed >> "$result"
      - run: |
          ssh -o StrictHostKeyChecking=no bdb2c2023q4_guest_3@brain-client.bigdatateam.org "mkdir ohiosstar && echo $result > ~/ohiosstar/task42.txt"
